In [1]:
from google.colab import files
uploaded = files.upload()

Saving T20 International Dataset.csv to T20 International Dataset (1).csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

df = pd.read_csv('T20 International Dataset.csv')
df

,Unnamed: 0,powerPlay,AverageScore,battingTeam,bowlingTeam,city,delivery_left,score,CurrentRunRate,wicketsLeft,Run_In_Last5,Wickets_In_Last5,Final_Score,innings
0,32266,0,153.142857,New Zealand,Sri Lanka,Colombo,51,94,8.173913,9,42.0,1.0,170,1
1,47001,0,158.307692,England,South Africa,Durban,0,204,10.200000,3,79.0,2.0,204,1
2,45705,0,158.307692,New Zealand,South Africa,Durban,23,79,4.886598,2,25.0,1.0,86,1
3,59293,1,149.000000,South Africa,New Zealand,Chattogram,85,39,6.685714,8,37.0,2.0,170,1
4,174494,0,137.000000,Pakistan,Sri Lanka,King City,79,44,6.439024,8,36.0,2.0,141,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131619,104582,0,149.275862,India,New Zealand,Johannesburg,57,103,9.809524,8,27.0,2.0,180,2
131620,50938,0,168.666667,Pakistan,New Zealand,Auckland,11,136,7.486239,3,57.0,2.0,153,1
131621,80339,0,130.714286,Zimbabwe,South Africa,Hambantota,69,40,4.705882,7,34.0,1.0,93,1
131622,99444,0,128.395349,Pakistan,England,Dubai,79,37,5.414634,7,27.0,2.0,146,2
131623,121673,1,135.609756,India,Sri Lanka,Colombo,89,46,8.903226,8,36.0,2.0,174,2

In [3]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)
index_names = df[ df['innings'] == 2 ].index
  
df.drop(index_names, inplace = True)
df.drop(['powerPlay','innings'],axis=1,inplace=True)
df

,AverageScore,battingTeam,bowlingTeam,city,delivery_left,score,CurrentRunRate,wicketsLeft,Run_In_Last5,Wickets_In_Last5,Final_Score
0,153.142857,New Zealand,Sri Lanka,Colombo,51,94,8.173913,9,42.0,1.0,170
1,158.307692,England,South Africa,Durban,0,204,10.200000,3,79.0,2.0,204
2,158.307692,New Zealand,South Africa,Durban,23,79,4.886598,2,25.0,1.0,86
3,149.000000,South Africa,New Zealand,Chattogram,85,39,6.685714,8,37.0,2.0,170
8,157.214286,Pakistan,Australia,Harare,16,95,5.480769,3,31.0,1.0,116
...,...,...,...,...,...,...,...,...,...,...,...
131616,153.882353,South Africa,New Zealand,Barbados,19,132,7.841584,7,54.0,1.0,170
131617,169.222222,New Zealand,Bangladesh,Mount Maunganui,37,102,7.373494,7,53.0,0.0,194
131618,152.800000,South Africa,New Zealand,London,53,79,7.074627,9,40.0,0.0,165
131620,168.666667,Pakistan,New Zealand,Auckland,11,136,7.486239,3,57.0,2.0,153
131621,130.714286,Zimbabwe,South Africa,Hambantota,69,40,4.705882,7,34.0,1.0,93

In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [6]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(55973, 10) (55973,)
(13994, 10) (13994,)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [8]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['battingTeam','bowlingTeam','city'])
]
,remainder='passthrough')

In [9]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [11]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

0.9892529790331703
1.6859829087452973

In [14]:
import pickle
pickle.dump(pipe,open(r"C:\Users\RUTHVIK\Desktop\internship\Innomatics proj\Productionize a ML Model\pipe.pkl",'wb'))